// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetSessionsByIdData, GetSessionsByIdErrors, GetSessionsByIdResponses, PostCallsData, PostCallsErrors, PostCallsResponses, PostSessionsBrowserData, PostSessionsBrowserErrors, PostSessionsBrowserResponses, PostSessionsByIdAnswerData, PostSessionsByIdAnswerErrors, PostSessionsByIdAnswerResponses, PostSessionsByIdEndData, PostSessionsByIdEndErrors, PostSessionsByIdEndResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postCalls = <ThrowOnError extends boolean = false>(options?: Options<PostCallsData, ThrowOnError>) => (options?.client ?? client).post<PostCallsResponses, PostCallsErrors, ThrowOnError>({
    url: '/calls',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postSessionsBrowser = <ThrowOnError extends boolean = false>(options?: Options<PostSessionsBrowserData, ThrowOnError>) => (options?.client ?? client).post<PostSessionsBrowserResponses, PostSessionsBrowserErrors, ThrowOnError>({
    url: '/sessions/browser',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getSessionsById = <ThrowOnError extends boolean = false>(options: Options<GetSessionsByIdData, ThrowOnError>) => (options.client ?? client).get<GetSessionsByIdResponses, GetSessionsByIdErrors, ThrowOnError>({ url: '/sessions/{id}', ...options });

export const postSessionsByIdAnswer = <ThrowOnError extends boolean = false>(options: Options<PostSessionsByIdAnswerData, ThrowOnError>) => (options.client ?? client).post<PostSessionsByIdAnswerResponses, PostSessionsByIdAnswerErrors, ThrowOnError>({
    url: '/sessions/{id}/answer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postSessionsByIdEnd = <ThrowOnError extends boolean = false>(options: Options<PostSessionsByIdEndData, ThrowOnError>) => (options.client ?? client).post<PostSessionsByIdEndResponses, PostSessionsByIdEndErrors, ThrowOnError>({ url: '/sessions/{id}/end', ...options });
