// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type StartCallResponse = {
    sessionId: string;
};

export type ErrorResponse = {
    error: string;
};

export type StartCallBody = {
    goal: string;
    phoneNumber: string;
};

export type StartBrowserSessionResponse = {
    sessionId: string;
};

export type StartBrowserSessionBody = {
    goal: string;
};

export type Session = {
    id: string;
    status: string;
    goal: string;
    transport: 'twilio' | 'browser';
    phoneNumber: string | null;
    pendingQuestion: {
        question: string;
        context: string;
    } | null;
    createdAt: string;
};

export type OkResponse = {
    ok: boolean;
};

export type SubmitAnswerBody = {
    answer: string;
};

export type PostCallsData = {
    body?: StartCallBody;
    path?: never;
    query?: never;
    url: '/calls';
};

export type PostCallsErrors = {
    /**
     * Validation error
     */
    400: ErrorResponse;
};

export type PostCallsError = PostCallsErrors[keyof PostCallsErrors];

export type PostCallsResponses = {
    /**
     * Call started
     */
    201: StartCallResponse;
};

export type PostCallsResponse = PostCallsResponses[keyof PostCallsResponses];

export type PostSessionsBrowserData = {
    body?: StartBrowserSessionBody;
    path?: never;
    query?: never;
    url: '/sessions/browser';
};

export type PostSessionsBrowserErrors = {
    /**
     * Validation error
     */
    400: ErrorResponse;
};

export type PostSessionsBrowserError = PostSessionsBrowserErrors[keyof PostSessionsBrowserErrors];

export type PostSessionsBrowserResponses = {
    /**
     * Browser session created
     */
    201: StartBrowserSessionResponse;
};

export type PostSessionsBrowserResponse = PostSessionsBrowserResponses[keyof PostSessionsBrowserResponses];

export type GetSessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type GetSessionsByIdErrors = {
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type GetSessionsByIdError = GetSessionsByIdErrors[keyof GetSessionsByIdErrors];

export type GetSessionsByIdResponses = {
    /**
     * Session state
     */
    200: Session;
};

export type GetSessionsByIdResponse = GetSessionsByIdResponses[keyof GetSessionsByIdResponses];

export type PostSessionsByIdAnswerData = {
    body?: SubmitAnswerBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}/answer';
};

export type PostSessionsByIdAnswerErrors = {
    /**
     * Validation error
     */
    400: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
    /**
     * No pending question
     */
    409: ErrorResponse;
    /**
     * Bridge not active
     */
    503: ErrorResponse;
};

export type PostSessionsByIdAnswerError = PostSessionsByIdAnswerErrors[keyof PostSessionsByIdAnswerErrors];

export type PostSessionsByIdAnswerResponses = {
    /**
     * Answer submitted
     */
    200: OkResponse;
};

export type PostSessionsByIdAnswerResponse = PostSessionsByIdAnswerResponses[keyof PostSessionsByIdAnswerResponses];

export type PostSessionsByIdEndData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}/end';
};

export type PostSessionsByIdEndErrors = {
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type PostSessionsByIdEndError = PostSessionsByIdEndErrors[keyof PostSessionsByIdEndErrors];

export type PostSessionsByIdEndResponses = {
    /**
     * Call ended
     */
    200: OkResponse;
};

export type PostSessionsByIdEndResponse = PostSessionsByIdEndResponses[keyof PostSessionsByIdEndResponses];
